# Unix submit description file

executable              = ../experiment.py
arguments               = "./data/2016/crafted/pop93_shuffled"
output                  = ./data/2016/crafted/pop93_shuffled.condout
errors                  = ./data/2016/crafted/pop93_shuffled.conderr
transfer_input_files    = ./data/2016/crafted/pop93_shuffled.cnf,./data/2016/crafted/pop93_shuffled.drat
transfer_output_files   = ./data/2016/crafted/pop93_shuffled.out,./data/2016/crafted/pop93_shuffled.DT.sick.SD.sick,./data/2016/crafted/pop93_shuffled.FD.sick
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue
