# Unix submit description file

executable              = ../experiment.py
arguments               = "./data/2016/app/snw_13_8_CCSpreOptpre"
output                  = ./data/2016/app/snw_13_8_CCSpreOptpre.condout
errors                  = ./data/2016/app/snw_13_8_CCSpreOptpre.conderr
transfer_input_files    = ./data/2016/app/snw_13_8_CCSpreOptpre.cnf,./data/2016/app/snw_13_8_CCSpreOptpre.drat
transfer_output_files   = ./data/2016/app/snw_13_8_CCSpreOptpre.out,./data/2016/app/snw_13_8_CCSpreOptpre.DT.sick.SD.sick,./data/2016/app/snw_13_8_CCSpreOptpre.FD.sick
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue
