# Unix submit description file

executable              = ../experiment.py
arguments               = "./data/2016/app/barman-pfile09-036.sas.cr.33"
output                  = ./data/2016/app/barman-pfile09-036.sas.cr.33.condout
errors                  = ./data/2016/app/barman-pfile09-036.sas.cr.33.conderr
transfer_input_files    = ./data/2016/app/barman-pfile09-036.sas.cr.33.cnf,./data/2016/app/barman-pfile09-036.sas.cr.33.drat
transfer_output_files   = ./data/2016/app/barman-pfile09-036.sas.cr.33.out,./data/2016/app/barman-pfile09-036.sas.cr.33.DT.sick.SD.sick,./data/2016/app/barman-pfile09-036.sas.cr.33.FD.sick
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue
